config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homepage#index'

  resources :users
  resources :user_sessions
  resources :runs
  resources :registrations

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  post '/registrations/register/:run_id' => 'registrations#register'
  delete '/registrations/unregister/:run_id' => 'registrations#unregister'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :run
  belongs_to :user

  validates :run, uniqueness: { scope: [:user] }
end

app/models/run.rb
class Run < ApplicationRecord
  has_many :registrations
  has_many :users, through: :registrations

  validates :starting_at, presence: true
  validates :registration_limit, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :registrations_booked, numericality: { greater_than_or_equal_to: 0, only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :name, presence: true

  has_many :registrations
  has_many :runs, through: :registrations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: 'Please sign in first'
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index
    if logged_in?
      redirect_to runs_path
    else
      render 'homepage/index'
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_run, only: [:register, :unregister]

  # POST /registrations
  def register
    confirmed = @run.registrations_booked < @run.registration_limit
    @registration = Registration.new(run_id: @run_id, user_id: current_user.id, confirmed: confirmed)

    if @registration.save
      update_registrations_booked 1
      redirect_to runs_path, notice: 'Registration was successfully created.'
    else
      redirect_to runs_path, notice: 'Registration was not successfully created.'
    end
  end

  # DELETE /registrations/1
  def unregister
    @registration = Registration.find_by_run_id_and_user_id(@run_id, current_user.id)
    place_will_free = @registration.confirmed
    @registration.destroy

    bump_first_user_on_waiting_list if place_will_free
    update_registrations_booked -1

    redirect_to runs_path, notice: 'Registration was successfully destroyed.'
  end

  private

  def update_registrations_booked(delta)
    @run.registrations_booked = @run.registrations_booked || 0
    @run.registrations_booked += delta
    @run.registrations_booked = @run.registrations_booked.negative? ? 0 : @run.registrations_booked
    @run.save
  end

  def bump_first_user_on_waiting_list
    first_user_on_waiting_list = Registration.where('confirmed = false').order('created_at ASC').first

    if first_user_on_waiting_list
      first_user_on_waiting_list.confirmed = true
      first_user_on_waiting_list.save
      WaitingListMailer.with(user: first_user_on_waiting_list.user, run: @run).notification_email.deliver_later
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_run
    @run_id = params['run_id']
    @run = Run.find_by_id(@run_id)
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  def index
    @runs = Run.all
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to('/', notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to('/', notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      @user = login(params[:email], params[:password])
      redirect_to :runs, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
  def set_action_button(run, user_id)
    run_user_registration = run.registrations.where(user_id: current_user.id)[0]
    if run_user_registration
      html = link_to 'Unregister', 'registrations/unregister/' + String(run.id),
                     method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
      html += if run_user_registration.confirmed
                ' <strong class="text-success">You place is confirmed</strong>'.html_safe
              else
                ' <strong class="text-warning">You are on the waiting list</strong>'.html_safe
              end
      html.html_safe
    else
      link_to 'Register', 'registrations/register/' + String(run.id), method: :post, class: 'btn btn-primary'
    end
  end
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/index.html.erb
<div class="text-center">
  <br>
  <h1>Do good, get fit</h1>
  <%= link_to "Get started", new_user_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/layouts/_topnav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <img src="/assets/goodgym-logo.png" width="90" height="40" alt="goodgym logo">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="navbar-text ml-auto">
          Hello <%= current_user.name %>!
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", :logout, method: :post, class: "nav-link text-danger" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign in", :login, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Goodgym</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render 'layouts/topnav'%>

    <div class="container">
      <br>

      <% if flash[:alert] %>
        <div class="alert alert-warning" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <% if flash[:notice] %>
        <div class="alert alert-primary" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/runs/index.html.erb
<h1>Runs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Starting at</th>
      <th>Registrations booked</th>
      <th>Registration limit</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @runs.each do |run| %>
      <tr>
        <td><%= run.starting_at %></td>
        <td><%= run.registrations_booked %></td>
        <td><%= run.registration_limit %></td>
        <td>
          <%= set_action_button(run,current_user.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/user_sessions/_form.html.erb
<%= form_with url: user_sessions_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <br><br>
  <div class="actions">
    <%= f.submit "Sign in", class:"btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<div class="row">
  <div class="col-md-4 offset-md-4 shadow">
    <br>
    <h1>Sign in</h1>
    <br>

    <%= render 'form' %>
    <br>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :password %><br />
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <br><br>
  <div class="actions">
    <%= form.submit "Get started", class:"btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-4 offset-md-4 shadow">
    <br>
    <h1>Sign up</h1>
    <br>

    <%= render 'form', user: @user %>
    <br>
  </div>
</div>